### PR TITLE
Message Verification Function completed

### PR DESCRIPTION
**Pull request by EbuBxl**

### CODE REVIEW

**Comment by EbuBxl** [comment]
Looking forward to your review!

**Review by Emelpoyraz — CHANGES_REQUESTED** [review]
please change the tag back @wip 
image

**Review by Emelpoyraz — COMMENTED** [review]
please change the credentials as it was, and remove the green part in your stepDefs.
image

**Comment by EbuBxl** [comment]
i have fulfilled your request for my PR...thx

**Review by Emelpoyraz — CHANGES_REQUESTED** [review]
thank you for correcting the configuration file. please change CukesRunner tag back to "@wip" and everything will be fine
image

**Comment by EbuBxl** [comment]
updated finally

**Review by Emelpoyraz — APPROVED** [review]

**Comment by Emelpoyraz** [comment]
wrong tag has been changed but I'll confirm this pull request ✌️

**Pull request merged**
